### PR TITLE
Silent mode (do not log requests with status == 200)

### PR DESCRIPTION
**Pull request by michaill**
Adding command option -s, --silent to stop logging successful requests.

### CODE REVIEW

**Comment by petrsloup** [comment]
Nice idea! Would it make sense to also skip 304 reponses?

**Comment by michaill** [comment]
I am glad you like it. My motivation was to minimize log output in our production and 304 responses never occur there. It is definitely good idea to add them, too. So here it is :)

**Comment by petrsloup** [comment]
Thanks!

**Comment by jxlarrea** [comment]
204 should also be added to this!

**Pull request merged**
