### PR TITLE
Support fontstacks.json

### PR DESCRIPTION
**Pull request by lukasmartinelli**
Supports fontstacks.json for #101. I don't want to dig into allowed fonts but this at least provides a fontstack.json

### CODE REVIEW

**Comment by petrsloup** [comment]
@lukasmartinelli Thanks for the PR, but I had to do it slightly differently -- listing `existingFonts` is not entirely correct, because these fonts may not be actually accessible (not allowed). See #101

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli Thanks for the PR, but I had to do it slightly differently -- listing existingFonts is not entirely correct, because these fonts may not be actually accessible (not allowed). See #101

Great! Thanks for implementing this Petr!

**Comment by petrsloup** [comment]
@lukasmartinelli Oh, I see there's been some confusion.. I implemented the json to be served on the root: https://free.tilehosting.com/fontstacks.json?key=Og58UhhtiiTaLVlPtPgs together with other "array" jsons (http://tileserver.readthedocs.io/en/latest/endpoints.html#tilejson-arrays). But I believe it's not a problem.. right?

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli Oh, I see there's been some confusion.. I implemented the json to be served on the root: https://free.tilehosting.com/fontstacks.json?key=Og58UhhtiiTaLVlPtPgs together with other "array" jsons (http://tileserver.readthedocs.io/en/latest/endpoints.html#tilejson-arrays). But I believe it's not a problem.. right?

In Maputnik I am infering the URL of the fontstacks JSON from the glyphs URL which for Tileserver GL needs to be `https://free.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}`.

Then I cut away the dynamic part `{fontstack}/{range}.pbf` part and ask for the fontstacks JSON there `https://free.tilehosting.com/fonts/fontstacks.json`.

I am not sure if that should be changed to the root from the Maputnik perspective since it makes it more difficult for serving fonts from GitHub (since you would always need a domain).

**Comment by lukasmartinelli** [comment]
What I mean is IMHO tileserver-gl should host the fontstacks.json at `fonts/fontstacks.json` because `fonts` is where the glyphs endpoint is.

**Comment by petrsloup** [comment]
Well, we have:
- `/styles/..` and 
- `/styles.json`
- `/data/...` and 
- `/data.json`

so `/fonts/...` and `/fonts.json` would actually make the most sense

**Comment by lukasmartinelli** [comment]
I need a consistent rule for Maputnik I can apply to the glyphs url - and it should also work when you just throw the font PBFs in GH Pages.

So it would always be the baseurl of the `glyphs` URL + `.json` extension?
That would be ok I guess.

**Comment by klokan** [comment]
+1 on `/fonts.json`.

It makes sense for TileServerGL.

How with hosting on github? 

https://fonts.openmaptiles.org/fontstacks.json
will become https://fonts.openmaptiles.org/fonts.json - you hit root, then "fonts.json" instead of ".json"?

**Comment by lukasmartinelli** [comment]
Having the rule depend on the root domain is not ideal. I still think it is better go relative from where the glyphs are stored.

Example (from OSM Liberty):

Glyphs URL: `https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf`

If you go to root it would try to request `orangemug.github.io/fonts.json` - an entirely different GitHub page and the process breaks down.

Instead go relative to `https://orangemug.github.io/font-glyphs/glyphs/fonts.json` which allows the user to put the `fonts.json` inside his GitHub page (or whatever other filename - i don't have an opinion whether call it `fonts` or `fontstacks`)

**Comment by klokan** [comment]
I suggest logic: replace `/{fontstack}/{range}.pbf*` with `.json`, unless you are on root of domain already - then use `/fontstacks.json`.

`https://free.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}` ->
`https://free.tilehosting.com/fonts.json`

`https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf` -> `https://orangemug.github.io/font-glyphs/glyphs.json`

`http://fonts.openmaptiles.org/{fontstack}/{range}.pbf` ->
`http://fonts.openmaptiles.org/fontstacks.json`

This is a change on the Maputnik side only, right?

**Comment by petrsloup** [comment]
Changed to `/fonts.json` in the latest release

**Comment by lukasmartinelli** [comment]
Hmm now I made a workaround especially for tileserver GL... so now I will need to change again. https://github.com/maputnik/editor/commit/404b53587f26b54002ed7d759b36698bb8bab342

Please tell me when it is deployed! Because then it will not work anymore until I've updated Maputnik again.

**Comment by petrsloup** [comment]
@lukasmartinelli It's deployed now.

**Pull request closed without merging**
